
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON FUN ID LBRACE LPAREN PRINTLN RBRACE RPAREN STRINGprogram : FUN ID LPAREN ID COLON STRING RPAREN LBRACE PRINTLN LPAREN STRING RPAREN RBRACE'
    
_lr_action_items = {'FUN':([0,],[2,]),'$end':([1,14,],[0,-1,]),'ID':([2,4,],[3,5,]),'LPAREN':([3,10,],[4,11,]),'COLON':([5,],[6,]),'STRING':([6,11,],[7,12,]),'RPAREN':([7,12,],[8,13,]),'LBRACE':([8,],[9,]),'PRINTLN':([9,],[10,]),'RBRACE':([13,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> FUN ID LPAREN ID COLON STRING RPAREN LBRACE PRINTLN LPAREN STRING RPAREN RBRACE','program',13,'p_program','lexico_sintactico.py',37),
]
